CREATE TABLE IF NOT EXISTS CURRENCY (
        ID BIGINT AUTO_INCREMENT NOT NULL COMMENT '貨幣id',
        CODE NVARCHAR(30) NOT NULL COMMENT '貨幣代號',
        CN_Name NVARCHAR(50) NOT NULL COMMENT '貨幣中文名稱',
        PRIMARY KEY (ID),
        UNIQUE (CODE)
);

